chmod 440 ./lab_0/dewgong4
chmod 444 ./lab_0/duskull0
chmod uo+r ./lab_0/fearow9
chmod g+w ./lab_0/fearow9
chmod u+x ./lab_0/fearow9
chmod uo-w ./lab_0/fearow9
chmod og-x ./lab_0/fearow9
chmod g-r ./lab_0/fearow9
chmod 600 ./lab_0/fearow9/beheeyem
chmod 330 ./lab_0/fearow9/marshtomp
chmod uo+r ./lab_0/fearow9/porygon
chmod g-rwx ./lab_0/fearow9/porygon
chmod uo-wx ./lab_0/fearow9/porygon
chmod 312 ./lab_0/glalie1
chmod ug+w ./lab_0/glalie1/electrode
chmod uog+x ./lab_0/glalie1/electrode
chmod go+r ./lab_0/glalie1/electrode
chmod u-r ./lab_0/glalie1/electrode
chmod o-w ./lab_0/glalie1/electrode
chmod 576 ./lab_0/glalie1/venipede
chmod 512 ./lab_0/glalie1/remoraid
chmod 512 ./lab_0/ponyta1
chmod 604 ./lab_0/ponyta1/kricketune
chmod 062 ./lab_0/ponyta1/zorua
chmod 600 ./lab_0/ponyta1/whirlpede
chmod ugo+wx ./lab_0/ponyta1/whimsicott
chmod g+r ./lab_0/ponyta1/whimsicott
chmod uo-r ./lab_0/ponyta1/whimsicott
chmod ugo+w ./lab_0/ponyta1/pichu
chmod u+r ./lab_0/ponyta1/pichu
chmod ugo-x ./lab_0/ponyta1/pichu
chmod go-r ./lab_0/ponyta1/pichu
chmod u-rwx ./lab_0/vibrava1
chmod go+r ./lab_0/vibrava1
chmod go-wx ./lab_0/vibrava1
