ORD 0x000  ;
V0:  	WORD  	$DEFAILT,  0x180  ;
V1:  	WORD  	$INT1,  0x180  ;
V2:  	WORD  	$INT2,  0x180  ;
V3:  	WORD  	$DEFAULT,  0x180  ;
V4:  	WORD  	$DEFAULT,  0x180  ;
V5:  	WORD  	$DEFAULT,  0x000  ;
V6:  	WORD  	$DEFAULT,  0x180  ;
V7:  	WORD  	$DEFAULT,  0x180  ;
DEFAULT:  	IRET  ;

ORD   0x013  ;
X:  	WORD  	0x000  ;

  ORD  0x040  ;
INT1:  	NOP  ;
  DI  ;
  PUSH  ;
  LD  	X  ;
  ASL  ;
  CALL  	CHECK  ;
  OUT  	0x02  ;
  NOP  ;
  POP  ;
  EI  ;
  IRET  ;

  ORD  0x050  ;
INT2: 	NOP  ;
  DI  ;
  IN  	0x04  ;
  NOT  ;
  OR  	X  ;
  NOT  ;
  CALL  	CHECK  ;
  ST  	X  ;
  EI  ;
  IRET  ;

  ORD   0x100  ;
MAX_VALUE: 	WORD  	0x003F  ;
MIN_VALUE: 	WORD  	0x0070  ;
START:  	DI  ;
  CLA  ;
LD  	#1  ;
  OUT  	3  ;
  LD  	#2  ;
  OUT  	5  ;
  EI  ;
MAIN:  	DI  ;
  LD  	X;
  INC  ;
  CALL  	CHECK  ;
  ST  	X;
  EI  ;
  JUMP  	MAIN  ;
CHECK:  	CMP  	MAX_VALUE  ;
  BMI  	MINUS  ;
  LD  	MIN_VALUE  ;
JUMP  	END  ;
MINUS:  	CMP  M	IN_VALUE  ;
BPL  	END  ;
  LD	MIN_VALUE  ;
END:  	RET  ;
